// Generated by deploy.bash — DO NOT EDIT
const CACHE_NAME = 'FoE:survey:main:260627.1125';
const APP_SHELL = [
  './',
  './shell-config.js',
  './index.html',
  './app.js',
  './sw.js',
  './version.json',
  './plants.json',
  './trails.json',
  './participants.json',
  './manifest.json',
  './icons/foe-icon-512.png',
  './icons/foe-icon-192.png',
  './foe-logo.png'
];
