#!/bin/bash
set -e

STAMP=$(TZ=America/Los_Angeles date +%y%m%d.%H%M)

BRANCH="${GITHUB_REF_NAME:-$(git rev-parse --abbrev-ref HEAD)}"
echo "Branch = $BRANCH"

if [ "$BRANCH" = "main" ]; then
  VERSION="V${STAMP}"
else
  VERSION="V${STAMP}(${BRANCH})"
fi

CACHE_NAME="FoE:survey-$VERSION"
STORAGE_TAG="FoE:survey:${BRANCH}"

# EMBEDDED CODE!  EDIT WITH CARE

cat > version.json <<EOF
{
  "branch": "$BRANCH",
  "version": "$VERSION",
  "storageTag": "$STORAGE_TAG"
}
EOF

# After VERSION is computed, generate shell-config.js

cat > shell-config.js <<EOF
// Generated by deploy.bash — DO NOT EDIT
const CACHE_NAME = '$CACHE_NAME';
const APP_SHELL = [
  './',
  './shell-config.js',
  './index.html',
  './app.js',
  './sw.js',
  './version.json',
  './plants.json',
  './trails.json',
  './participants.json',
  './manifest.json',
  './icons/foe-icon-512.png',
  './icons/foe-icon-192.png',
  './foe-logo.png'
];
EOF

# Then prepend to sw.js.in
cat shell-config.js sw.js.in > sw.js

# END EMBEDDED CODE

# Icon Handling
IM="magick"
if ! command -v magick >/dev/null 2>&1; then
  IM="convert"
fi

$IM icons/foe-icon-192-base.png \
  -fill orange \
  -stroke white \
  -strokewidth 1.5 \
  -draw "circle 168,24 168,12" \
  icons/foe-icon-192.png

if [ "$BRANCH" = "dev" ]; then
  $IM icons/foe-icon-192-base.png \
    -fill orange \
    -stroke white \
    -strokewidth 1.5 \
    -draw "circle 168,24 168,12" \
    icons/foe-icon-192.png
  $IM icons/foe-icon-512-base.png \
    -fill orange \
    -stroke white \
    -strokewidth 4 \
    -draw "circle 448,64 448,32" \
    icons/foe-icon-512.png
else
  cp icons/foe-icon-192-base.png icons/foe-icon-192.png
  cp icons/foe-icon-512-base.png icons/foe-icon-512.png
fi
