// Generated by deploy.bash — DO NOT EDIT
const CACHE_NAME = 'FoE:survey:dev:260627.1745';
const APP_SHELL = [
  './',
  './shell-config.js',
  './index.html',
  './app.js',
  './sw.js',
  './version.json',
  './data/plants.json',
  './data/trails.json',
  './data/participants.json',
  './manifest.json',
  './icons/foe-icon-512.png',
  './icons/foe-icon-192.png',
  './icons/foe-logo.png'
];
