// Generated by deploy.bash — DO NOT EDIT
const CACHE_NAME = 'FoE:survey:dev:260721.0807';
const APP_SHELL = [
  './',
  './shell-config.js',
  './index.html',
  './app.js',
  './sw.js',
  './version.json',
  './data/plants.json',
  './data/trails.json',
  './data/participants.json',
  './manifest.json',
  './icons/foe-icon-512.png',
  './icons/foe-icon-192.png',
  './icons/foe-logo.png'
];

if (!CACHE_NAME || typeof CACHE_NAME !== 'string') {
  throw new Error('CACHE_NAME not injected');
}

self.addEventListener('install', handleInstall);

self.addEventListener('activate', handleActivate);

self.addEventListener('fetch', handleFetch);

// Explicit activation: the page must postMessage {type: 'SKIP_WAITING'}
// to request the new worker activate. Do NOT call skipWaiting() here
// automatically to avoid mid-survey activation.
self.addEventListener('message', (event) => {
  try {
    const msg = event.data;

    if (msg && msg.type === 'GET_CACHE_INFO') {
      const reply = {type: 'CACHE_INFO', cacheName: CACHE_NAME};
  
      if (event.ports[0])
        event.ports[0].postMessage(reply);
      else
        event.source?.postMessage(reply);

    } else if (msg && msg.type === 'SKIP_WAITING') {
      console.log('SW: SKIP_WAITING message received');
      self.skipWaiting();
    }
  } catch (e) {
    console.warn('SW message handler error', e);
  }
});

// INSTALL
async function handleInstall(event) {
  // Populate cache during install but DO NOT skipWaiting here.
  event.waitUntil( cacheAppShell());
}

async function cacheAppShell() {
  const cache = await caches.open(CACHE_NAME);

  await Promise.all(
    APP_SHELL.map(async file => {
      console.log( 'caching:', file);

      const response = await fetch(file, { cache: "reload" });
      if (!response.ok) {
        throw new Error(`Failed ${file}`);
      }

      await cache.put(file, response);
    })
  );
}

// ACTIVATE
function handleActivate(event) {
  event.waitUntil(deleteOldCaches());
}

async function deleteOldCaches() {
  const cachePrefix = cacheFamilyPrefix(CACHE_NAME);
  if (!cachePrefix) {
    console.warn('SW: could not identify cache family for', CACHE_NAME);
    await clients.claim();
    return;
  }

  const keys = await caches.keys();

  await Promise.all(
    keys.map(key => {
      if (key !== CACHE_NAME && key.startsWith(cachePrefix)) {
        console.warn('SW: deleting old cache for this branch:', key);
        return caches.delete(key);
      }

      return Promise.resolve(false);
    })
  );

  await clients.claim();
}

function cacheFamilyPrefix(cacheName) {
  const match = cacheName.match(/^FoE:survey:([^:]+):/);
  if (!match)
    return null;

  return `FoE:survey:${match[1]}:`;
}

// FETCH
function handleFetch(event) {
  const rq = event.request;

  // only same-origin GET
  if (rq.method !== 'GET' || new URL(rq.url).origin !== location.origin) {
    return;
  }
  event.respondWith(fetchFromCache(rq));
}

async function fetchFromCache(request) {

  if (request.cache === 'reload') {
    return fetch(request);
  }

  const cache = await caches.open(CACHE_NAME);
  const cached = await cache.match(request);

  if (cached) {
    return cached;
  }

  console.warn('SW: cache miss:', CACHE_NAME, request.url);

  const miss = {
    error: "cache-miss",
    cacheName: CACHE_NAME,
    url: request.url,
    method: request.method,
    mode: request.mode,
    destination: request.destination,
    cache: request.cache,
    credentials: request.credentials,
    redirect: request.redirect,
    referrer: request.referrer
  };

  return new Response(
    JSON.stringify(miss, null, 2),
    {
      status: 504,
      statusText: "Survey Tool cache miss",
      headers: {
        "Content-Type": "application/json; charset=utf-8",
        "Cache-Control": "no-store"
      }
    }
  );
}
